# -*- coding: utf-8 -*-
"""Phase_Field_Simulation_New_Work_Part3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wq4mQ9Y3jVscP9Q_glq4uVNGpv00MH2U
"""

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 15
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
##############
R0 = 5.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
################################################################################
P = -Pr * np.ones((Nx, Ny))
def Initial_Polarization():
  #P = -Pr * np.ones((Nx, Ny))
  # Center
  r_center = np.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)
  # Corners (quarter circles due to Neumann BC)
  r_corners = [
    np.sqrt((X - 0)**2     + (Y - 0)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - 0)**2),
    np.sqrt((X - 0)**2     + (Y - (Ny-1))**2),
    np.sqrt((X - (Nx-1))**2 + (Y - (Ny-1))**2),
    ]
  P_center = Pr*np.tanh((R0-r_center)/w)
  mask_center = r_center < R0 + 3*w
  P[mask_center] = P_center[mask_center]
  for r in r_corners:
    P_corner = Pr * np.tanh((R0 - r) / w)
    mask_corner = r < R0 + 3*w
    P[mask_corner] = P_corner[mask_corner]
  return P
###################################################
P=Initial_Polarization()
###################################################
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

###################################################################################
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
###############################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.savefig('foo.png')
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

#######################################################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet',vmin=-Pr, vmax=Pr)
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 22
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
##############
R0 = 5.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
################################################################################
P = -Pr * np.ones((Nx, Ny))
def Initial_Polarization():
  #P = -Pr * np.ones((Nx, Ny))
  # Center
  r_center = np.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)
  # Corners (quarter circles due to Neumann BC)
  r_corners = [
    np.sqrt((X - 0)**2     + (Y - 0)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - (Ny-1))**2),
    ]
  P_center = Pr*np.tanh((R0-r_center)/w)
  mask_center = r_center < R0 + 3*w
  P[mask_center] = P_center[mask_center]
  for r in r_corners:
    P_corner = Pr * np.tanh((R0 - r) / w)
    mask_corner = r < R0 + 3*w
    P[mask_corner] = P_corner[mask_corner]
  return P
###################################################
P=Initial_Polarization()
###################################################
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

###################################################################################
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
###############################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

#######################################################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 22
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
##############
R0 = 5.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
################################################################################
P = -Pr * np.ones((Nx, Ny))
def Initial_Polarization():
  #P = -Pr * np.ones((Nx, Ny))
  # Center
  r_center = np.sqrt((X-Nx//2)**2 + (Y-Ny//2)**2)
  # Corners (quarter circles due to Neumann BC)
  r_corners = [
    np.sqrt((X - (Nx-1))**2 + (Y - 0)**2),
    np.sqrt((X - 0)**2     + (Y - (Ny-1))**2),
    ]
  P_center = Pr*np.tanh((R0-r_center)/w)
  mask_center = r_center < R0 + 3*w
  P[mask_center] = P_center[mask_center]
  for r in r_corners:
    P_corner = Pr * np.tanh((R0 - r) / w)
    mask_corner = r < R0 + 3*w
    P[mask_corner] = P_corner[mask_corner]
  return P
###################################################
P=Initial_Polarization()
###################################################
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

###################################################################################
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
###############################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

#######################################################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 22
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
##############
R0 = 5.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
################################################################################
P = -Pr * np.ones((Nx, Ny))
def Initial_Polarization():
  #P = -Pr * np.ones((Nx, Ny))
  # Center
  r_center = np.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)
  # Corners (quarter circles due to Neumann BC)
  r_corners = [
    np.sqrt((X - 0)**2     + (Y - 0)**2),
    np.sqrt((X - Nx//2)**2     + (Y - 0)**2),
    np.sqrt((X - Nx//2)**2     + (Y - Ny-1//2)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - 0)**2),
    np.sqrt((X - 0)**2     + (Y - (Ny-1))**2),
    np.sqrt((X - (Nx-1))**2 + (Y - (Ny-1))**2),
    ]
  P_center = Pr*np.tanh((R0-r_center)/w)
  mask_center = r_center < R0 + 3*w
  P[mask_center] = P_center[mask_center]
  for r in r_corners:
    P_corner = Pr * np.tanh((R0 - r) / w)
    mask_corner = r < R0 + 3*w
    P[mask_corner] = P_corner[mask_corner]
  return P
###################################################
P=Initial_Polarization()
###################################################
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

###################################################################################
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
###############################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

#######################################################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 22
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
##############
R0 = 5.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
################################################################################
P = -Pr * np.ones((Nx, Ny))
def Initial_Polarization():
  #P = -Pr * np.ones((Nx, Ny))
  # Center
  r_center = np.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)
  # Corners (quarter circles due to Neumann BC)
  r_corners = [
    np.sqrt((X - 0)**2     + (Y - 0)**2),
    np.sqrt((X - Nx//2)**2     + (Y - 0)**2),
    np.sqrt((X - Nx//2)**2     + (Y - Ny-1//2)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - 0)**2),
    np.sqrt((X - 0)**2     + (Y - (Ny-1))**2),
    np.sqrt((X - 0)**2 + (Y - Ny//2)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - (Ny-1)//2)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - (Ny-1))**2),
    ]
  P_center = Pr*np.tanh((R0-r_center)/w)
  mask_center = r_center < R0 + 3*w
  P[mask_center] = P_center[mask_center]
  for r in r_corners:
    P_corner = Pr * np.tanh((R0 - r) / w)
    mask_corner = r<R0+3*w
    P[mask_corner] = P_corner[mask_corner]
  return P
###################################################
P=Initial_Polarization()
###################################################
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

###################################################################################
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
###############################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

#######################################################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  #P_snap=np.clip(P_snap.T,-Pr,Pr)
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet',vmin=-Pr, vmax=Pr)
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 15
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
##############
R0 = 10.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
################################################################################
P = -Pr * np.ones((Nx, Ny))
def Initial_Polarization():
  #P = -Pr * np.ones((Nx, Ny))
  # Center
  r_center = np.sqrt((X - Nx//2)**2 + (Y - Ny//2)**2)
  # Corners (quarter circles due to Neumann BC)
  r_corners = [
    np.sqrt((X - 0)**2     + (Y - 0)**2),
    np.sqrt((X - (Nx-1))**2 + (Y - 0)**2),
    np.sqrt((X - 0)**2     + (Y - (Ny-1))**2),
    np.sqrt((X - (Nx-1))**2 + (Y - (Ny-1))**2),
    ]
  P_center = Pr*np.tanh((R0-r_center)/w)
  mask_center = r_center < R0 + 3*w
  P[mask_center] = P_center[mask_center]
  return P
  #for r in r_corners:
   # P_corner = Pr * np.tanh((R0 - r) / w)
    #mask_corner = r < R0 + 3*w
    #P[mask_corner] = P_corner[mask_corner]
  #return P
###################################################
P=Initial_Polarization()
###################################################
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

###################################################################################
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
###############################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

#######################################################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet',vmin=-Pr, vmax=Pr)
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

import numpy as np
import matplotlib.pyplot as plt

alpha = -1.499
beta = 0.498
gamma = 0.001

def polarization(P):
    return alpha*P + beta*P**3 + gamma*P**5

P = np.linspace(-1.732, 1.732, 20)
E = polarization(P)

plt.plot(E,P)
plt.xlabel("Polarization P Electric field E")
plt.ylabel("Electric field E")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

alpha = -1.499
beta = 0.498
gamma = 0.001

def polarization(P):
    return alpha*P + beta*P**3 + gamma*P**5

P = np.linspace(-2, 2, 500)
E = polarization(P)

plt.plot(E,P)
plt.xlabel("Electric field E")
plt.ylabel("Polarization P")
plt.show()