# -*- coding: utf-8 -*-
"""Phase_Field_Simulation_2D_Part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1csa13TLa36C15bSoo3Xj6OYhd75-F8Vf
"""

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator scheme with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 22
Pr = 1.732
#########################################################
E0 = 0.9
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
xc, yc = Nx // 2, Ny // 2 # Centre of circle is exactly half of x and y-dimension
r = np.sqrt((X-xc)**2+(Y-yc)**2)

R0 = 10.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
##############################################
'''
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
'''
#################################################
def update_P(P, E):
    lapP = (
        np.roll(P,  1, axis=0) +
        np.roll(P, -1, axis=0) +
        np.roll(P,  1, axis=1) +
        np.roll(P, -1, axis=1)
        - 4.0 * P
    ) / dx**2

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho

    return P + dt * dPdt
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#######################
#Code for case II
#######################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
xc, yc = 0, 0 # Centre of circle is exactly at the left corner of x and y-dimension
r = np.sqrt((X-xc)**2+(Y-yc)**2)

R0 = 15.0      # Initial radius (change to probe sub/supercritical)
#w  = 2.0       # DW width
P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
##################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()

##############################################################
P_avg_time2=np.array(P_avg_time)
P_avg_pulse2=np.array(P_avg_pulse)
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-ii")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
#############################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#######################
#Code for case III
#######################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
xc, yc = Nx//4, Ny//2 # Centre of circle is exactly at the left corner of x and y-dimension
r = np.sqrt((X-xc)**2+(Y-yc)**2)

#R0 = 15.0      # Initial radius (change to probe sub/supercritical)
#w  = 2.0       # DW width
P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
##################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
######################################
##############################################################
P_avg_time3=np.array(P_avg_time)
P_avg_pulse3=np.array(P_avg_pulse)
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-iii")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
#############################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

#######################
#Code for case III
#######################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
xc, yc = Nx//4, Ny//4 # Centre of circle is exactly at the left corner of x and y-dimension
r = np.sqrt((X-xc)**2+(Y-yc)**2)

#R0 = 15.0      # Initial radius (change to probe sub/supercritical)
#w  = 2.0       # DW width
P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
##################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()

##############################################################
P_avg_time4=np.array(P_avg_time)
P_avg_pulse4=np.array(P_avg_pulse)
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-iv")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
#############################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

######################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time1, '--k',label='Case-i')
plt.plot(Time*1e-3, P_avg_time2, '--m',label='Case-ii')
plt.plot(Time*1e-3, P_avg_time3, '--g',label='Case-iii')
plt.plot(Time*1e-3, P_avg_time4, '--r',label='Case-iv')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.legend(loc="upper left")
plt.grid()
plt.show()
############################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse1, '-*k',label='Case-i')
plt.plot(P_avg_pulse2, '-og',label='Case-ii')
plt.plot(P_avg_pulse3, '-sb',label='Case-iii')
plt.plot(P_avg_pulse4, '-*r',label='Case-iv')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.legend(loc="upper left")
plt.grid()
plt.show()