# -*- coding: utf-8 -*-
"""Phase_Field_Simulation_2D_Neumann_Part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-Wh6OIMv06HkMnh78t_SnRi25I29nin
"""

#Phase Field Modeling and polarization accumulation in HZO Sample
#Under the influence of square wave pulse train
# Here We have integrated TDGL equation using Euler integrator with Finite Element Based space discretization scheme
#################################################
import numpy as np
import matplotlib.pyplot as plt
##################################################
Nx = Ny = 80
dx = 1.0
dt = 0.1
total_time = 6000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
############################################################
alpha, beta, gamma = -1.499, 0.498, 0.001
K = 1.0
rho = 22
Pr = 1.732
#########################################################
E0 = 0.8
ton = 100
toff = 400
period = ton + toff

E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
xc, yc = Nx//2, Ny//2 # Centre of circle is exactly half of x and y-dimension
r = np.sqrt((X-xc)**2+(Y-yc)**2)

R0 = 12.0      # initial radius (change to probe sub/supercritical)
w  = 2.0       # DW width
P = Pr*np.tanh((R0-r)/ w) #########Polarization Initialization
print("Initial <P> =", P.mean())
Initial_confi=P.copy()
##############################################
'''
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
'''
################################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)

    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

####################
E0 = [0.6,0.7,0.8,1.0,1.2]
E_field = np.zeros((len(E0), n_steps))
for i, t in enumerate(Time):
  if (t % period) < ton:
        #print('Index',i)
        E_field[0,i] = E0[0]
        E_field[1,i] = E0[1]
        E_field[2,i] = E0[2]
        E_field[3,i] = E0[3]
        E_field[4,i] = E0[4]
        #ton_index.append(i)
  else:
    E_field[0,i] = 0.0
    E_field[1,i] = 0.0
    E_field[2,i] = 0.0
    E_field[3,i] = 0.0
    E_field[4,i] = 0.0
##############################################
pulse_end_index = []
in_pulse = False

for n, t in enumerate(Time):
    if (t % period) < ton:
        in_pulse = True
    else:
        if in_pulse:
            pulse_end_index.append(n-1)
        in_pulse = False

################################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  xc, yc = Nx//2, Ny//2 # Centre of circle is exactly half of x and y-dimension
  r = np.sqrt((X-xc)**2+(Y-yc)**2)
  R0 = 15.0      # initial radius (change to probe sub/supercritical)
  w  = 2.0       # DW width
  P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
  return P
################################################
P_avg_time=np.zeros((len(E0), n_steps))
n_pulses = len(pulse_end_index)
P_avg_pulse = np.zeros((len(E0), n_pulses))
#P_avg_pulse.shape
for i in range(len(E0)):
  P=Intial_polarization()
  #E_field1=E_field[i,:]
  pulse_counter = 0
  for n in range(n_steps):
    P = update_P(P, E_field[i,n])
    #R_t[n] = compute_radius(P)
    #P_avg_time.append(np.mean(P))
    P_avg_time[i,n]=np.mean(P)
    if n in list(map(int, ton_index)):
      #print('n_step',n)
      pulse_number = ton_index.index(n)
      #print('pulse_numer',pulse_number)
      P_avg_pulse[i,pulse_number]=np.mean(P)
    #if pulse_counter < n_pulses and n == pulse_end_index[pulse_counter]:
     #       P_avg_pulse[i, pulse_counter] = np.mean(P)
      #      pulse_counter += 1
  #if n in Pulse_index:
     #   snapshots[n] = P.copy()
#############################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
#################################
#P_time = np.array(P_time)
plt.plot(Time,P_avg_time[0,:],'r',label="E0=0.6")
plt.plot(Time,P_avg_time[1,:],'b',label="E0=0.7")
plt.plot(Time,P_avg_time[2,:],'g',label="E0=0.8")
plt.plot(Time,P_avg_time[3,:],'y',label="E0=1.0")
plt.plot(Time,P_avg_time[4,:],'--k',label="E0=1.2")
plt.figtext(0.75, 0.2,
            r"$T_{on}=0.1$ $\mu$s; $T_{off}=0.4$ $\mu$s",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"Time, $t$ (ns)")
plt.ylabel(r"$\bar{P}_n (t)$")
plt.legend(loc=(0.75, 0.30))
plt.grid()
plt.tight_layout()
#plt.legend(loc="upper left")
plt.show()
#P.shape()

plt.plot(P_avg_pulse[0,:],'-r*',label='E0=0.6')
plt.plot(P_avg_pulse[1,:],'-b*',label='E0=0.7')
plt.plot(P_avg_pulse[2,:],'-g*',label='E0=0.8')
plt.plot(P_avg_pulse[3,:],'-y*',label='E0=1.0')
plt.plot(P_avg_pulse[4,:],'-k*',label='E0=1.2')
plt.figtext(0.75, 0.25,
            r"$T_{on}=0.1$ $\mu$s; $T_{off}=0.4$ $\mu$s",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"No of Pulses, $j$")
plt.ylabel(r"$P^{acc}_n$")
plt.legend(loc=(0.75, 0.20))
plt.grid()
plt.tight_layout()
plt.show()

# Following code is with three Field pulses of different Ton; Toff=50 ns for all
# Electric Field pulse train
E0 = 0.8
total_time = 7200
dt = 0.1
n_steps = int(total_time/dt)
num_pulses = 12
ton=[50,75,100,150,200]
toff=400
pulse_end_indices = np.zeros((len(ton),num_pulses))
Time = np.arange(0, total_time, dt)
#E0=[0.8,1.0,1.2]
E_field = np.zeros((len(ton), n_steps))
#ton=[50,70,90]
#toff=50
############################################
for i in range(len(ton)):
  for n in range(num_pulses):
    start_idx = int(n * (ton[i] + toff) / dt)
    end_idx = int(start_idx + ton[i]/dt)
    if end_idx > n_steps:
      end_idx = n_steps
    #E_field[start_idx:end_idx] = E0
    pulse_end_indices[i,n]=end_idx - 1  # store last index of pulse
###########################################################################
'''pulse_end_indices = np.zeros((len(ton), num_pulses), dtype=int)

for i in range(len(ton)):
    period = ton[i] + toff
    for p in range(num_pulses):
        end_time = p * period + ton[i]
        pulse_end_indices[i, p] = int(end_time / dt)
'''
################################################################

###########################################
P_avg_end = np.zeros((len(ton), num_pulses))
P_avg=np.zeros((len(ton), n_steps))
###############################################

# Generate pulse trains
for i in range(len(ton)):
    period = ton[i] + toff
    for n, t in enumerate(Time):
        if (t % period) < ton[i]:
            E_field[i, n] = E0
        else:
            E_field[i, n] = 0.0
'''
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
'''
###############################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  xc, yc = Nx//2, Ny//2 # Centre of circle is exactly half of x and y-dimension
  r = np.sqrt((X-xc)**2+(Y-yc)**2)
  R0 = 15.0      # initial radius (change to probe sub/supercritical)
  w  = 2.0       # DW width
  P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
  return P
#########################################################
P_avg_time=np.zeros((len(ton), n_steps))
P_avg_pulse = np.zeros((len(ton), n_pulses))
########################################################
for i in range(len(ton)):
  pulse_counter=0
  P=Intial_polarization()
  #Efield=E_field[i,:]
  for n in range(n_steps):
    P = update_P(P, E_field[i,n])
    #R_t[n] = compute_radius(P)
    #P_avg_time.append(np.mean(P))
    P_avg_time[i,n]=np.mean(P)
    if n in pulse_end_indices[i,:]:
      pulse_number = int(pulse_end_indices[i,pulse_counter])
      #print(pulse_number)
      #pulse_counter+=1
      P_avg_pulse[i,pulse_counter] = P.mean()
      pulse_counter+=1
    #if pulse_counter < n_pulses and n == pulse_end_index[pulse_counter]:
     #       P_avg_pulse[i, pulse_counter] = np.mean(P)
      #      pulse_counter += 1
  #if n in Pulse_index:
     #   snapshots[n] = P.copy()
#############################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
#################################
#P_time = np.array(P_time)
plt.plot(Time,P_avg_time[0,:],'r',label=r"$T_{on}=50$ ns")
plt.plot(Time,P_avg_time[1,:],'b',label=r"$T_{on}=75$ ns")
plt.plot(Time,P_avg_time[2,:],'g',label=r"$T_{on}=100$ ns")
plt.plot(Time,P_avg_time[3,:],'y',label=r"$T_{on}=150$ ns")
plt.plot(Time,P_avg_time[4,:],'--k',label=r"$T_{on}=200$ ns")
plt.figtext(0.75, 0.2,
            r"$T_{off}=400$ nss; $E_{o}=0.8$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"Time, $t$ (ns)")
plt.ylabel(r"$\bar{P}_n (t)$")
plt.legend(loc=(0.75, 0.30))
plt.grid()
plt.tight_layout()
#plt.legend(loc="upper left")
plt.show()
#P.shape()

plt.plot(P_avg_pulse[0,:],'-r*',label=r"$T_{on}=50$ ns")
plt.plot(P_avg_pulse[1,:],'-b*',label=r"$T_{on}=75$ ns")
plt.plot(P_avg_pulse[2,:],'-g*',label=r"$T_{on}=100$ ns")
plt.plot(P_avg_pulse[3,:],'-y*',label=r"$T_{on}=150$ ns")
plt.plot(P_avg_pulse[4,:],'-k*',label=r"$T_{on}=200$ ns")
plt.figtext(0.75, 0.25,
            r"$T_{off}=400$ ns; $E_{o}=0.8$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"No of Pulses, $j$")
plt.ylabel(r"$P^{acc}_n$")
plt.legend(loc=(0.75, 0.20))
plt.grid()
plt.tight_layout()
plt.show()

# Following code is with three Field pulses of different Toff; Ton=50 ns for all
# Electric Field pulse train
E0 = 0.8
total_time = 9600
dt = 0.1
n_steps = int(total_time/dt)
num_pulses = 12
toff=[300,400,500,600,700]
ton=100
pulse_end_indices = np.zeros((len(toff),num_pulses))
Time = np.arange(0, total_time, dt)
#E0=[0.8,1.0,1.2]
E_field = np.zeros((len(toff), n_steps))
#ton=[50,70,90]
#toff=50
############################################
for i in range(len(toff)):
  for n in range(num_pulses):
    start_idx = int(n * (ton+ toff[i])/dt)
    end_idx = int(start_idx + toff[i]/dt)
    if end_idx > n_steps:
      end_idx = n_steps
    #E_field[start_idx:end_idx] = E0
    pulse_end_indices[i,n]=end_idx - 1  # store last index of pulse
###########################################################################
'''pulse_end_indices = np.zeros((len(ton), num_pulses), dtype=int)

for i in range(len(ton)):
    period = ton[i] + toff
    for p in range(num_pulses):
        end_time = p * period + ton[i]
        pulse_end_indices[i, p] = int(end_time / dt)
'''
################################################################

###########################################
P_avg_end = np.zeros((len(toff), num_pulses))
P_avg=np.zeros((len(toff), n_steps))
###############################################

# Generate pulse trains
for i in range(len(toff)):
    period = toff[i] + ton
    for n, t in enumerate(Time):
        if (t % period) < toff[i]:
            E_field[i, n] = 0
        else:
            E_field[i, n] = E0
###############################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  xc, yc = Nx//2, Ny//2 # Centre of circle is exactly half of x and y-dimension
  r = np.sqrt((X-xc)**2+(Y-yc)**2)
  R0 = 15.0      # initial radius (change to probe sub/supercritical)
  w  = 2.0       # DW width
  P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
  return P
#########################################################
P_avg_time=np.zeros((len(toff), n_steps))
P_avg_pulse = np.zeros((len(toff), n_pulses))
########################################################
for i in range(len(toff)):
  pulse_counter=0
  P=Intial_polarization()
  #Efield=E_field[i,:]
  for n in range(n_steps):
    P = update_P(P, E_field[i,n])
    #R_t[n] = compute_radius(P)
    #P_avg_time.append(np.mean(P))
    P_avg_time[i,n]=np.mean(P)
    if n in pulse_end_indices[i,:]:
      pulse_number = int(pulse_end_indices[i,pulse_counter])
      #print(pulse_number)
      #pulse_counter+=1
      P_avg_pulse[i,pulse_counter] = P.mean()
      pulse_counter+=1
    #if pulse_counter < n_pulses and n == pulse_end_index[pulse_counter]:
     #       P_avg_pulse[i, pulse_counter] = np.mean(P)
      #      pulse_counter += 1
  #if n in Pulse_index:
     #   snapshots[n] = P.copy()
#############################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
#################################
#P_time = np.array(P_time)
plt.plot(Time,P_avg_time[0,:],'r',label=r"$T_{off}=300$ ns")
plt.plot(Time,P_avg_time[1,:],'b',label=r"$T_{off}=450$ ns")
plt.plot(Time,P_avg_time[2,:],'g',label=r"$T_{off}=500$ ns")
plt.plot(Time,P_avg_time[3,:],'y',label=r"$T_{off}=600$ ns")
plt.plot(Time,P_avg_time[4,:],'--k',label=r"$T_{off}=700$ ns")
plt.figtext(0.75, 0.2,
            r"$T_{on}=100$ ns; $E_{o}=0.8$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"Time, $t$ (ns)")
plt.ylabel(r"$\bar{P}_n (t)$")
plt.legend(loc=(0.75, 0.30))
plt.grid()
plt.tight_layout()
#plt.legend(loc="upper left")
plt.show()
#P.shape()

plt.plot(P_avg_pulse[0,:],'-r*',label=r"$T_{off}=300$ ns")
plt.plot(P_avg_pulse[1,:],'-b*',label=r"$T_{off}=450$ ns")
plt.plot(P_avg_pulse[2,:],'-g*',label=r"$T_{off}=500$ ns")
plt.plot(P_avg_pulse[3,:],'-y*',label=r"$T_{off}=600$ ns")
plt.plot(P_avg_pulse[4,:],'-k*',label=r"$T_{off}=700$ ns")
plt.figtext(0.75, 0.25,
            r"$T_{on}=100$ ns; $E_{o}=0.8$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"No of Pulses, $j$")
plt.ylabel(r"$P^{acc}_n$")
plt.legend(loc=(0.75, 0.20))
plt.grid()
plt.tight_layout()
plt.show()

#######################
import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter
Pr=1.732
Nx,Ny=80,80
dx = 1.0
dt = 0.05
total_time = 3000
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
# Generate data
mu=1.0
sigma=0.125
#rng = np.random.default_rng(seed=42)
#Ec = rng.normal(loc=1, scale=0.125, size=Nx*Ny)
Ec=np.random.normal(loc=mu, scale=sigma, size=Nx*Ny)
#plt.hist(Ec, bins=50, density=True)
gamma=-(0.5*(Ec*Pr**2-3*Ec))/(Pr**2-1)**2
alpha=gamma-1.5*Ec
beta=-2*gamma+0.5*Ec
#plt.hist(gamma, bins=50, density=True)
#plt.show()
#plt.hist(alpha, bins=50, density=True)
#plt.show()
#plt.hist(beta, bins=50, density=True)
#plt.show()
###########################################################
#Converting 1D array of alpha, beta and gamma to 2D array
###########################################################
'''
alpha = alpha.reshape(Nx, Ny)
beta = beta.reshape(Nx, Ny)
gamma = gamma.reshape(Nx, Ny)
'''
##################################################

# --- EC generation ---
Ec = np.random.normal(mu, sigma, (Nx,Ny))
Ec = gaussian_filter(Ec, sigma=4)

x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])

Ec*= (1 - 0.3*np.exp(-dist_edge/5))

# --- Landau coefficients ---
alpha = -1.499 * Ec / Ec.mean()
beta  = 0.498 * np.ones_like(alpha)
gamma = 0.001 * np.ones_like(alpha)

# --- Initial condition ---
P = -Pr * np.ones((Nx,Ny))
P[dist_edge < 2] += 0.02*np.random.randn(*(P[dist_edge < 2].shape))

#########################################################
E0 = 0.92
ton = 100
toff = 400
period = ton + toff
K=1.0
rho=22.0
E_field = np.zeros_like(Time)
ton_index=[]
toff_index=[]
for i, t in enumerate(Time):
    if (t % period) < ton:
        E_field[i] = E0
        #ton_index.append(i)
    else:
        E_field[i] = 0.0
        #toff_index.append(i)
##################################################
'''
ton_index.append(int(pulse_on/dt))
toff_index.append(int((pulse_on+pulse_off)/dt))
j=int(pulse_on/dt)
k=int((pulse_on+pulse_off)/dt)
for i in enumerate(Time):
  j=j+(pulse_on+pulse_off)/dt
  k=k+(pulse_on+pulse_off)/dt
  ton_index.append(j)
  toff_index.append(k)
'''
ton_index.append(int(ton/dt))
toff_index.append(int((ton+toff)/dt))
j=int(ton/dt)
k=int((ton+toff)/dt)
for i in range(0,int(total_time/dt),int(period/dt)):
  j=j+(ton+toff)/dt
  k=k+(ton+toff)/dt
  ton_index.append(j)
  toff_index.append(k)
########################
print("Pulse on times:", ton_index)
print("Pulse off times:", toff_index)
Pulse_index=np.concatenate((ton_index,toff_index))
Pulse_index=np.sort(Pulse_index)
print(Pulse_index)
##############################################
#x = np.arange(Nx)
#y = np.arange(Ny)
#X, Y = np.meshgrid(x, y, indexing='ij')
#xc, yc = Nx//2, Ny//2 # Centre of circle is exactly half of x and y-dimension
#r = np.sqrt((X-xc)**2+(Y-yc)**2)

#R0 = 12.0      # initial radius (change to probe sub/supercritical)
#w  = 2.0       # DW width
#P = Pr*np.tanh((R0-r)/ w) #########Polarization Initialization
#print("Initial <P> =", P.mean())
#Initial_confi=P.copy()
#P[:,:] =-Pr
#print("Average",np.mean(P))
#Initial_confi=P.copy()
##############################################
'''
plt.figure(figsize=(6,5))
plt.imshow(P.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
'''
################################################################
def laplacian_neumann(P, dx):
    lapP = np.zeros_like(P)

    # Interior points
    lapP[1:-1, 1:-1] = (
        P[2:, 1:-1] + P[:-2, 1:-1] +
        P[1:-1, 2:] + P[1:-1, :-2]
        - 4.0 * P[1:-1, 1:-1]
    ) / dx**2

    # Edges (zero normal gradient)
    lapP[0, 1:-1] = (
        P[1, 1:-1] + P[0, 1:-1] +
        P[0, 2:] + P[0, :-2]
        - 4.0 * P[0, 1:-1]
    ) / dx**2

    lapP[-1, 1:-1] = (
        P[-2, 1:-1] + P[-1, 1:-1] +
        P[-1, 2:] + P[-1, :-2]
        - 4.0 * P[-1, 1:-1]
    ) / dx**2

    lapP[1:-1, 0] = (
        P[2:, 0] + P[:-2, 0] +
        P[1:-1, 1] + P[1:-1, 0]
        - 4.0 * P[1:-1, 0]
    ) / dx**2

    lapP[1:-1, -1] = (
        P[2:, -1] + P[:-2, -1] +
        P[1:-1, -2] + P[1:-1, -1]
        - 4.0 * P[1:-1, -1]
    ) / dx**2

    # Corners
    lapP[0, 0] = (
        P[1, 0] + P[0, 0] +
        P[0, 1] + P[0, 0]
        - 4.0 * P[0, 0]
    ) / dx**2

    lapP[0, -1] = (
        P[1, -1] + P[0, -1] +
        P[0, -2] + P[0, -1]
        - 4.0 * P[0, -1]
    ) / dx**2

    lapP[-1, 0] = (
        P[-2, 0] + P[-1, 0] +
        P[-1, 1] + P[-1, 0]
        - 4.0 * P[-1, 0]
    ) / dx**2

    lapP[-1, -1] = (
        P[-2, -1] + P[-1, -1] +
        P[-1, -2] + P[-1, -1]
        - 4.0 * P[-1, -1]
    ) / dx**2

    return lapP

################################################################

#################################################
def update_P(P, E):
    lapP = laplacian_neumann(P, dx)
    #print("Dimension of alpha array",alpha.shape)
    dPdt = -(
        alpha * P
        + beta  * P**3
        + gamma * P**5
        - K * lapP
        - E
    ) / rho
    return P+dt*dPdt # Euler Update for each value of applied electric field
#########################################################################
def compute_radius(P):
    mask = P > 0.0
    area = mask.sum()*dx**2
    return np.sqrt(area/np.pi)
################################################################
snapshots = {}
R_t = np.zeros(n_steps)
P_avg_time = []  # to store <P> vs time
P_avg_pulse=[]
for n in range(n_steps):
    P = update_P(P, E_field[n])
    R_t[n] = compute_radius(P)
    P_avg_time.append(np.mean(P))
    if n in ton_index:
        P_avg_pulse.append(np.mean(P))
    if n in Pulse_index:
        snapshots[n] = P.copy()
##############################################################
P_avg_time1=np.array(P_avg_time)
P_avg_pulse1=np.array(P_avg_pulse)
#############################################################
'''
# (a) Radius vs time
plt.figure(figsize=(6,4))
plt.plot(Time, R_t, 'k')
plt.xlabel("Time")
plt.ylabel("Domain radius R")
plt.title("Fig. 5: Circular domain evolution")
plt.grid()
plt.show()
'''
#########################################################
plt.hist(gamma, bins=50, density=True)
plt.show()
plt.hist(alpha, bins=50, density=True)
plt.show()
plt.hist(beta, bins=50, density=True)
plt.show()
########################################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
####################################
plt.figure(figsize=(6,5))
plt.imshow(Initial_confi.T, origin='lower', cmap='jet', aspect='equal')
plt.colorbar(label='P')
plt.title("Initial polarization map: Case-i")
plt.xlabel("x")
plt.ylabel("y")
plt.show()
#####################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, P_avg_time, 'r')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"$\bar{P}_n(t)$")
plt.grid()
plt.show()
############################################
########################################################
plt.figure(figsize=(6,2))
plt.plot(P_avg_pulse, '-*r')
plt.xlabel("No of pulses, j")
plt.ylabel(r"${P}^{acc}_n$")
plt.grid()
plt.show()
##############################################
###############################################
'''
for P_snap in snapshots.values():
    plt.figure(figsize=(6,4))
    plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
    plt.colorbar(label='P')
    #plt.title(f'P-map at t = {step*dt:.1f} ns')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.show()
'''
###################################################

# P-map plot at the last of instant of Ton and Toff (for all the pulses)
i=0 # Time counter
for P_snap in snapshots.values():
  step=Time[int(Pulse_index[i])]*1e-3
  plt.figure(figsize=(6,4))
  plt.imshow(P_snap.T, origin='lower', aspect='auto', cmap='jet')
  plt.colorbar(label='P')
  plt.title(fr'P-map at t = {step:.1f} $\mu$ s')
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
  i=i+1

####################
Pr=1.732
Nx,Ny=80,80
dx = 1.0
dt = 0.05
total_time = 3500
Time = np.arange(0, total_time, dt)
n_steps = len(Time)
###############################
E0 = [0.86,0.88,0.92,0.95,1.1]
E_field = np.zeros((len(E0), n_steps))
for i, t in enumerate(Time):
  if (t % period) < ton:
        #print('Index',i)
        E_field[0,i] = E0[0]
        E_field[1,i] = E0[1]
        E_field[2,i] = E0[2]
        E_field[3,i] = E0[3]
        E_field[4,i] = E0[4]
        #ton_index.append(i)
  else:
    E_field[0,i] = 0.0
    E_field[1,i] = 0.0
    E_field[2,i] = 0.0
    E_field[3,i] = 0.0
    E_field[4,i] = 0.0
##############################################
pulse_end_index = []
in_pulse = False

for n, t in enumerate(Time):
    if (t % period) < ton:
        in_pulse = True
    else:
        if in_pulse:
            pulse_end_index.append(n-1)
        in_pulse = False

################################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])
  P = -Pr * np.ones((Nx,Ny))
  P[dist_edge < 2] += 0.02*np.random.randn(*(P[dist_edge < 2].shape))
  return P
###############################################
Ec = np.random.normal(mu, sigma, (Nx,Ny))
Ec = gaussian_filter(Ec, sigma=4)

x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])

Ec*= (1 - 0.3*np.exp(-dist_edge/5))

alpha = -1.499 * Ec / Ec.mean()
beta  = 0.498 * np.ones_like(alpha)
gamma = 0.001 * np.ones_like(alpha)

################################################
P_avg_time=np.zeros((len(E0), n_steps))
n_pulses = len(pulse_end_index)
P_avg_pulse = np.zeros((len(E0), n_pulses))
#P_avg_pulse.shape
for i in range(len(E0)):
  P=Intial_polarization()
  #E_field1=E_field[i,:]
  pulse_counter = 0
  for n in range(n_steps):
    P = update_P(P, E_field[i,n])
    #R_t[n] = compute_radius(P)
    #P_avg_time.append(np.mean(P))
    P_avg_time[i,n]=np.mean(P)
    if n in list(map(int, ton_index)):
      #print('n_step',n)
      pulse_number = ton_index.index(n)
      #print('pulse_numer',pulse_number)
      P_avg_pulse[i,pulse_number]=np.mean(P)
    #if pulse_counter < n_pulses and n == pulse_end_index[pulse_counter]:
     #       P_avg_pulse[i, pulse_counter] = np.mean(P)
      #      pulse_counter += 1
  #if n in Pulse_index:
     #   snapshots[n] = P.copy()
#############################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
#################################
#P_time = np.array(P_time)
plt.plot(Time,P_avg_time[0,:],'r',label="E0=0.86")
plt.plot(Time,P_avg_time[1,:],'b',label="E0=0.88")
plt.plot(Time,P_avg_time[2,:],'g',label="E0=0.88")
plt.plot(Time,P_avg_time[3,:],'y',label="E0=0.95")
plt.plot(Time,P_avg_time[4,:],'--k',label="E0=1.1")
plt.figtext(0.75, 0.2,
            r"$T_{on}=0.1$ $\mu$s; $T_{off}=0.4$ $\mu$s",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"Time, $t$ (ns)")
plt.ylabel(r"$\bar{P}_n (t)$")
plt.legend(loc=(0.75, 0.30))
plt.grid()
plt.tight_layout()
#plt.legend(loc="upper left")
plt.show()
#P.shape()

plt.plot(P_avg_pulse[0,:],'-r*',label='E0=0.86')
plt.plot(P_avg_pulse[1,:],'-b*',label='E0=0.88')
plt.plot(P_avg_pulse[2,:],'-g*',label='E0=0.92')
plt.plot(P_avg_pulse[3,:],'-y*',label='E0=0.95')
plt.plot(P_avg_pulse[4,:],'-k*',label='E0=1.1')
plt.figtext(0.75, 0.25,
            r"$T_{on}=0.1$ $\mu$s; $T_{off}=0.4$ $\mu$s",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"No of Pulses, $j$")
plt.ylabel(r"$P^{acc}_n$")
plt.legend(loc=(0.75, 0.20))
plt.grid()
plt.tight_layout()
plt.show()

# Following code is with three Field pulses of different Ton; Toff=50 ns for all
# Electric Field pulse train
E0 = 0.92
total_time = 3180
dt = 0.1
n_steps = int(total_time/dt)
num_pulses = 6
ton=[90,100,110,120,130]
toff=400
pulse_end_indices = np.zeros((len(ton),num_pulses))
Time = np.arange(0, total_time, dt)
#E0=[0.8,1.0,1.2]
E_field = np.zeros((len(ton), n_steps))
#ton=[50,70,90]
#toff=50
############################################
for i in range(len(ton)):
  for n in range(num_pulses):
    start_idx = int(n * (ton[i] + toff) / dt)
    end_idx = int(start_idx + ton[i]/dt)
    if end_idx > n_steps:
      end_idx = n_steps
    #E_field[start_idx:end_idx] = E0
    pulse_end_indices[i,n]=end_idx - 1  # store last index of pulse
###########################################################################
'''pulse_end_indices = np.zeros((len(ton), num_pulses), dtype=int)

for i in range(len(ton)):
    period = ton[i] + toff
    for p in range(num_pulses):
        end_time = p * period + ton[i]
        pulse_end_indices[i, p] = int(end_time / dt)
'''
################################################################

###########################################
P_avg_end = np.zeros((len(ton), num_pulses))
P_avg=np.zeros((len(ton), n_steps))
###############################################

# Generate pulse trains
for i in range(len(ton)):
    period = ton[i] + toff
    for n, t in enumerate(Time):
        if (t % period) < ton[i]:
            E_field[i, n] = E0
        else:
            E_field[i, n] = 0.0
'''
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
'''
###############################################
################################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])
  P = -Pr * np.ones((Nx,Ny))
  P[dist_edge < 2] += 0.02*np.random.randn(*(P[dist_edge < 2].shape))
  return P
###############################################
Ec = np.random.normal(mu, sigma, (Nx,Ny))
Ec = gaussian_filter(Ec, sigma=4)

x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])

Ec*= (1 - 0.3*np.exp(-dist_edge/5))

alpha = -1.499 * Ec / Ec.mean()
beta  = 0.498 * np.ones_like(alpha)
gamma = 0.001 * np.ones_like(alpha)

#########################################################
P_avg_time=np.zeros((len(ton), n_steps))
P_avg_pulse = np.zeros((len(ton), n_pulses))
########################################################
for i in range(len(ton)):
  pulse_counter=0
  P=Intial_polarization()
  #Efield=E_field[i,:]
  for n in range(n_steps):
    P = update_P(P, E_field[i,n])
    #R_t[n] = compute_radius(P)
    #P_avg_time.append(np.mean(P))
    P_avg_time[i,n]=np.mean(P)
    if n in pulse_end_indices[i,:]:
      pulse_number = int(pulse_end_indices[i,pulse_counter])
      #print(pulse_number)
      #pulse_counter+=1
      P_avg_pulse[i,pulse_counter] = P.mean()
      pulse_counter+=1
    #if pulse_counter < n_pulses and n == pulse_end_index[pulse_counter]:
     #       P_avg_pulse[i, pulse_counter] = np.mean(P)
      #      pulse_counter += 1
  #if n in Pulse_index:
     #   snapshots[n] = P.copy()
#############################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
#################################
#P_time = np.array(P_time)
plt.plot(Time,P_avg_time[0,:],'r',label=r"$T_{on}=90$ ns")
plt.plot(Time,P_avg_time[1,:],'b',label=r"$T_{on}=100$ ns")
plt.plot(Time,P_avg_time[2,:],'g',label=r"$T_{on}=110$ ns")
plt.plot(Time,P_avg_time[3,:],'y',label=r"$T_{on}=120$ ns")
plt.plot(Time,P_avg_time[4,:],'--k',label=r"$T_{on}=130$ ns")
plt.figtext(0.75, 0.2,
            r"$T_{off}=400$ nss; $E_{o}=0.92$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"Time, $t$ (ns)")
plt.ylabel(r"$\bar{P}_n (t)$")
plt.legend(loc=(0.75, 0.30))
plt.grid()
plt.tight_layout()
#plt.legend(loc="upper left")
plt.show()
#P.shape()

plt.plot(P_avg_pulse[0,:],'-r*',label=r"$T_{on}=90$ ns")
plt.plot(P_avg_pulse[1,:],'-b*',label=r"$T_{on}=100$ ns")
plt.plot(P_avg_pulse[2,:],'-g*',label=r"$T_{on}=110$ ns")
plt.plot(P_avg_pulse[3,:],'-y*',label=r"$T_{on}=120$ ns")
plt.plot(P_avg_pulse[4,:],'-k*',label=r"$T_{on}=130$ ns")
plt.figtext(0.75, 0.25,
            r"$T_{off}=400$ ns; $E_{o}=0.92$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"No of Pulses, $j$")
plt.ylabel(r"$P^{acc}_n$")
plt.legend(loc=(0.75, 0.20))
plt.grid()
plt.tight_layout()
plt.show()

# Following code is with three Field pulses of different Toff; Ton=50 ns for all
# Electric Field pulse train
E0 = 0.92
total_time = 5400
dt = 0.1
n_steps = int(total_time/dt)
num_pulses = 6
toff=[200,400,600,750,800]
ton=100
pulse_end_indices = np.zeros((len(toff),num_pulses))
Time = np.arange(0, total_time, dt)
#E0=[0.8,1.0,1.2]
E_field = np.zeros((len(toff), n_steps))
#ton=[50,70,90]
#toff=50
############################################
for i in range(len(toff)):
  for n in range(num_pulses):
    start_idx = int(n * (ton+ toff[i])/dt)
    end_idx = int(start_idx + toff[i]/dt)
    if end_idx > n_steps:
      end_idx = n_steps
    #E_field[start_idx:end_idx] = E0
    pulse_end_indices[i,n]=end_idx - 1  # store last index of pulse
###########################################################################
'''pulse_end_indices = np.zeros((len(ton), num_pulses), dtype=int)

for i in range(len(ton)):
    period = ton[i] + toff
    for p in range(num_pulses):
        end_time = p * period + ton[i]
        pulse_end_indices[i, p] = int(end_time / dt)
'''
################################################################
################################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])
  P = -Pr * np.ones((Nx,Ny))
  P[dist_edge < 2] += 0.02*np.random.randn(*(P[dist_edge < 2].shape))
  return P
###############################################
Ec = np.random.normal(mu, sigma, (Nx,Ny))
Ec = gaussian_filter(Ec, sigma=4)

x = np.arange(Nx)
y = np.arange(Ny)
X, Y = np.meshgrid(x, y, indexing='ij')
dist_edge = np.minimum.reduce([X, Y, Nx-1-X, Ny-1-Y])

Ec*= (1 - 0.3*np.exp(-dist_edge/5))

alpha = -1.499 * Ec / Ec.mean()
beta  = 0.498 * np.ones_like(alpha)
gamma = 0.001 * np.ones_like(alpha)

#########################################################
###########################################
P_avg_end = np.zeros((len(toff), num_pulses))
P_avg=np.zeros((len(toff), n_steps))
###############################################

# Generate pulse trains
for i in range(len(toff)):
    period = toff[i] + ton
    for n, t in enumerate(Time):
        if (t % period) < toff[i]:
            E_field[i, n] = 0
        else:
            E_field[i, n] = E0
###############################################
#Polarization_Initialization
def Intial_polarization():
  x = np.arange(Nx)
  y = np.arange(Ny)
  X, Y = np.meshgrid(x, y, indexing='ij')
  xc, yc = Nx//2, Ny//2 # Centre of circle is exactly half of x and y-dimension
  r = np.sqrt((X-xc)**2+(Y-yc)**2)
  R0 = 15.0      # initial radius (change to probe sub/supercritical)
  w  = 2.0       # DW width
  P = Pr * np.tanh((R0 - r)/ w) #########Polarization Initialization
  return P
#########################################################
P_avg_time=np.zeros((len(toff), n_steps))
P_avg_pulse = np.zeros((len(toff), n_pulses))
########################################################
for i in range(len(toff)):
  pulse_counter=0
  P=Intial_polarization()
  #Efield=E_field[i,:]
  for n in range(n_steps):
    P = update_P(P, E_field[i,n])
    #R_t[n] = compute_radius(P)
    #P_avg_time.append(np.mean(P))
    P_avg_time[i,n]=np.mean(P)
    if n in pulse_end_indices[i,:]:
      pulse_number = int(pulse_end_indices[i,pulse_counter])
      #print(pulse_number)
      #pulse_counter+=1
      P_avg_pulse[i,pulse_counter] = P.mean()
      pulse_counter+=1
    #if pulse_counter < n_pulses and n == pulse_end_index[pulse_counter]:
     #       P_avg_pulse[i, pulse_counter] = np.mean(P)
      #      pulse_counter += 1
  #if n in Pulse_index:
     #   snapshots[n] = P.copy()
#############################################
plt.figure(figsize=(6,2))
plt.plot(Time*1e-3, E_field[0,:], 'r')
plt.plot(Time*1e-3, E_field[1,:], 'g')
plt.plot(Time*1e-3, E_field[2,:], 'b')
plt.plot(Time*1e-3, E_field[3,:], 'y')
plt.plot(Time*1e-3, E_field[4,:], '--k')
plt.xlabel(r"Time, $t$ ($\mu$s)")
plt.ylabel(r"${E}^{app}_n$")
plt.grid()
plt.show()
#################################
#P_time = np.array(P_time)
plt.plot(Time,P_avg_time[0,:],'r',label=r"$T_{off}=200$ ns")
plt.plot(Time,P_avg_time[1,:],'b',label=r"$T_{off}=400$ ns")
plt.plot(Time,P_avg_time[2,:],'g',label=r"$T_{off}=600$ ns")
plt.plot(Time,P_avg_time[3,:],'y',label=r"$T_{off}=750$ ns")
plt.plot(Time,P_avg_time[4,:],'--k',label=r"$T_{off}=800$ ns")
plt.figtext(0.75, 0.2,
            r"$T_{on}=100$ ns; $E_{o}=0.92$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"Time, $t$ (ns)")
plt.ylabel(r"$\bar{P}_n (t)$")
plt.legend(loc=(0.75, 0.30))
plt.grid()
plt.tight_layout()
#plt.legend(loc="upper left")
plt.show()
#P.shape()

plt.plot(P_avg_pulse[0,:],'-r*',label=r"$T_{off}=200$ ns")
plt.plot(P_avg_pulse[1,:],'-b*',label=r"$T_{off}=400$ ns")
plt.plot(P_avg_pulse[2,:],'-g*',label=r"$T_{off}=600$ ns")
plt.plot(P_avg_pulse[3,:],'-y*',label=r"$T_{off}=750$ ns")
plt.plot(P_avg_pulse[4,:],'-k*',label=r"$T_{off}=800$ ns")
plt.figtext(0.75, 0.25,
            r"$T_{on}=100$ ns; $E_{o}=0.92$",
            horizontalalignment ="center",
            verticalalignment ="center",
            wrap = True, fontsize = 14,
            color ="green")
plt.xlabel(r"No of Pulses, $j$")
plt.ylabel(r"$P^{acc}_n$")
plt.legend(loc=(0.75, 0.20))
plt.grid()
plt.tight_layout()
plt.show()